"use client";

import React, { useEffect, useState } from "react";
import { AlertCircle, Loader2, Lock, LogOut, Plus, Save, Trash2 } from "lucide-react";
import type { ArticleItem, CampaignItem, CampaignStatus, ClinicSettings, FAQItem, PriceType, ServiceCategory, ServiceItem } from "@/types";
import { isSupabaseConfigured, supabase } from "@/lib/supabase/client";

type Tab = "clinic" | "services" | "campaigns" | "faqs" | "articles";
type ClinicTextKey = Exclude<keyof ClinicSettings, "requiresAppointment">;
type Props = { initialClinic: ClinicSettings; initialServices: ServiceItem[]; initialCategories: ServiceCategory[]; initialFaqs: FAQItem[]; initialCampaigns: CampaignItem[]; initialArticles: ArticleItem[] };

const btn = "inline-flex items-center gap-2 rounded-xl bg-petrol-900 px-4 py-2 text-xs font-semibold text-white hover:bg-petrol-800 disabled:opacity-60";
const btn2 = "inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50";

function Input({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (v: string) => void; type?: string }) {
  return <label className="space-y-1 text-xs font-semibold text-slate-600"><span>{label}</span><input type={type} value={value} onChange={e => onChange(e.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal text-slate-900" /></label>;
}
function Area({ label, value, onChange, rows = 3 }: { label: string; value: string; onChange: (v: string) => void; rows?: number }) {
  return <label className="space-y-1 text-xs font-semibold text-slate-600"><span>{label}</span><textarea rows={rows} value={value} onChange={e => onChange(e.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-normal text-slate-900" /></label>;
}
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) {
  return <label className="flex items-center gap-2 text-xs font-medium text-slate-700"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} />{label}</label>;
}

export function AdminDashboardV2({ initialClinic, initialServices, initialCategories, initialFaqs, initialCampaigns, initialArticles }: Props) {
  const [ready, setReady] = useState(false), [login, setLogin] = useState(false), [busy, setBusy] = useState(false);
  const [email, setEmail] = useState(""), [password, setPassword] = useState(""), [error, setError] = useState<string | null>(null), [msg, setMsg] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>("clinic"), [clinicId, setClinicId] = useState<string | null>(null);
  const [clinic, setClinic] = useState(initialClinic), [categories, setCategories] = useState(initialCategories), [services, setServices] = useState(initialServices), [faqs, setFaqs] = useState(initialFaqs), [campaigns, setCampaigns] = useState(initialCampaigns), [articles, setArticles] = useState(initialArticles);
  const client = supabase;
  const ok = (text: string) => { setMsg(text); window.setTimeout(() => setMsg(null), 2500); };

  async function isAdmin(userId: string) {
    if (!client) return false;
    const { data, error: e } = await client.from("admin_profiles").select("id,role").eq("id", userId).maybeSingle();
    return !e && !!data && data.role === "admin";
  }
  async function load() {
    if (!client) return;
    setBusy(true); setError(null);
    const [c, cats, s, f, cp, a] = await Promise.all([
      client.from("clinic_settings").select("*").order("created_at").limit(1).maybeSingle(),
      client.from("service_categories").select("*").order("display_order"), client.from("services").select("*").order("display_order"),
      client.from("faqs").select("*").order("display_order"), client.from("campaigns").select("*").order("display_order"), client.from("articles").select("*").order("display_order")
    ]);
    const e = c.error || cats.error || s.error || f.error || cp.error || a.error;
    if (e) { setError(e.message); setBusy(false); return; }
    const cc: ServiceCategory[] = (cats.data || []).map(x => ({ id:x.id, slug:x.slug, name:x.name, description:x.description || undefined, displayOrder:x.display_order || 0, isActive:x.is_active ?? true }));
    setCategories(cc); const names = new Map(cc.map(x => [x.slug, x.name]));
    if (c.data) { const x=c.data; setClinicId(x.id); setClinic({ name:x.name, shortDescription:x.short_description||undefined, logo:x.logo_url||undefined, whatsapp:x.whatsapp||undefined, phone:x.phone||undefined, email:x.email||undefined, address:x.address||undefined, mapsUrl:x.maps_url||undefined, openingHours:x.opening_hours||undefined, emergencyCare:x.emergency_care||undefined, emergencyReferenceContact:x.emergency_reference_contact||undefined, acceptedSpecies:x.accepted_species||undefined, paymentMethods:x.payment_methods||undefined, instagram:x.instagram||undefined, responsibleVeterinarian:x.responsible_veterinarian||undefined, crmv:x.crmv||undefined, city:x.city||undefined, neighborhood:x.neighborhood||undefined, requiresAppointment:x.requires_appointment??true, lastPriceReviewDate:x.last_price_review_date||undefined, priceDisclaimer:x.price_disclaimer||undefined }); }
    setServices((s.data||[]).map(x => ({ id:x.id, categorySlug:x.category_slug, categoryName:names.get(x.category_slug)||x.category_slug, name:x.name, shortDescription:x.short_description, priceType:x.price_type as PriceType, exactPrice:x.exact_price==null?null:Number(x.exact_price), startingPrice:x.starting_price==null?null:Number(x.starting_price), requiresEvaluation:x.requires_evaluation??false, evaluationNotes:x.evaluation_notes||undefined, includedItems:x.included_items||[], observations:x.observations||undefined, availability:x.availability||"Sob agendamento", isActive:x.is_active??true, displayOrder:x.display_order||0 })));
    setFaqs((f.data||[]).map(x => ({ id:x.id, category:x.category, categoryName:x.category, question:x.question, answer:x.answer, displayOrder:x.display_order||0, isActive:x.is_active??true })));
    setCampaigns((cp.data||[]).map(x => ({ id:x.id, slug:x.slug, title:x.title, folderImageUrl:x.folder_image_url||undefined, summary:x.summary, fullDescription:x.full_description, startDate:x.start_date, endDate:x.end_date, eligibleAudience:x.eligible_audience||undefined, includedServices:x.included_services||[], realPriceOrCondition:x.real_price_or_condition, rulesAndLimitations:x.rules_and_limitations, downloadFileUrl:x.download_file_url||undefined, status:x.status as CampaignStatus, displayOrder:x.display_order||0 })));
    setArticles((a.data||[]).map(x => ({ id:x.id, slug:x.slug, title:x.title, summary:x.summary, category:x.category, content:x.content, revisionDate:x.revision_date, technicalReviewerName:x.technical_reviewer_name||undefined, technicalReviewerCrmv:x.technical_reviewer_crmv||undefined, isPublished:x.is_published??true, displayOrder:x.display_order||0 })));
    setBusy(false);
  }
  useEffect(() => { if (!isSupabaseConfigured || !client) { setLogin(true); return; } client.auth.getSession().then(async ({data}) => { if (!data.session || !(await isAdmin(data.session.user.id))) { if (data.session) await client.auth.signOut(); setLogin(true); return; } setReady(true); await load(); }); }, []); // eslint-disable-line react-hooks/exhaustive-deps

  async function signIn(e: React.FormEvent) { e.preventDefault(); if (!client || !isSupabaseConfigured) return setError("Configure o Supabase antes de usar o painel."); setBusy(true); setError(null); const r=await client.auth.signInWithPassword({email:email.trim(),password}); if (r.error || !r.data.user || !(await isAdmin(r.data.user.id))) { await client.auth.signOut(); setError(r.error?.message || "Usuário sem permissão administrativa."); setBusy(false); return; } setReady(true); setLogin(false); setPassword(""); await load(); setBusy(false); }
  async function saveClinic() { if(!client)return; setBusy(true); const p={name:clinic.name,short_description:clinic.shortDescription||null,logo_url:clinic.logo||null,whatsapp:clinic.whatsapp||null,phone:clinic.phone||null,email:clinic.email||null,address:clinic.address||null,maps_url:clinic.mapsUrl||null,opening_hours:clinic.openingHours||null,emergency_care:clinic.emergencyCare||null,emergency_reference_contact:clinic.emergencyReferenceContact||null,accepted_species:clinic.acceptedSpecies||null,payment_methods:clinic.paymentMethods||null,instagram:clinic.instagram||null,responsible_veterinarian:clinic.responsibleVeterinarian||null,crmv:clinic.crmv||null,city:clinic.city||null,neighborhood:clinic.neighborhood||null,requires_appointment:clinic.requiresAppointment??true,last_price_review_date:clinic.lastPriceReviewDate||null,price_disclaimer:clinic.priceDisclaimer||null,updated_at:new Date().toISOString()}; const r=clinicId?await client.from("clinic_settings").update(p).eq("id",clinicId):await client.from("clinic_settings").insert(p).select("id").single(); if(r.error)setError(r.error.message); else { if(!clinicId && r.data) setClinicId((r.data as {id:string}).id); ok("Clínica salva."); } setBusy(false); }
  async function save(table: "services"|"faqs"|"campaigns"|"articles", payload: object) { if(!client)return false; setBusy(true); const {error:e}=await client.from(table).upsert(payload,{onConflict:"id"}); setBusy(false); if(e){setError(e.message);return false;} ok("Alterações salvas."); return true; }
  async function del(table: "services"|"faqs"|"campaigns"|"articles", id:string) { if(!client || !confirm("Excluir este item?"))return false; const {error:e}=await client.from(table).delete().eq("id",id); if(e){setError(e.message);return false;} ok("Item excluído."); return true; }

  if (!isSupabaseConfigured) return <div className="mx-auto max-w-xl rounded-2xl border border-amber-200 bg-amber-50 p-8 text-center"><Lock className="mx-auto mb-3"/><h1 className="font-bold">Painel bloqueado</h1><p className="mt-2 text-sm text-slate-600">O site está em modo estático. Configure NEXT_PUBLIC_SUPABASE_URL e NEXT_PUBLIC_SUPABASE_ANON_KEY para habilitar a administração.</p></div>;
  if (!ready || login) return <form onSubmit={signIn} className="mx-auto max-w-md space-y-4 rounded-2xl border border-slate-200 bg-white p-7 shadow-card"><h1 className="text-center text-xl font-bold">Acesso administrativo</h1>{error&&<p className="flex gap-2 rounded-lg bg-rose-50 p-3 text-xs text-rose-700"><AlertCircle className="h-4 w-4"/>{error}</p>}<Input label="E-mail" value={email} onChange={setEmail} type="email"/><Input label="Senha" value={password} onChange={setPassword} type="password"/><button disabled={busy} className={`${btn} w-full justify-center`}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Lock className="h-4 w-4"/>}Entrar</button></form>;

  const tabs: [Tab,string][]=[["clinic","Clínica"],["services",`Serviços (${services.length})`],["campaigns",`Campanhas (${campaigns.length})`],["faqs",`Dúvidas (${faqs.length})`],["articles",`Informativos (${articles.length})`]];
  const cf: [ClinicTextKey,string][]=[["name","Nome"],["shortDescription","Descrição"],["whatsapp","WhatsApp"],["phone","Telefone"],["email","E-mail"],["instagram","Instagram"],["address","Endereço"],["mapsUrl","Google Maps"],["openingHours","Horários"],["emergencyCare","Urgência / 24h"],["emergencyReferenceContact","Referência de emergência"],["acceptedSpecies","Espécies"],["paymentMethods","Pagamento"],["responsibleVeterinarian","Responsável técnico"],["crmv","CRMV"],["city","Cidade/UF"],["neighborhood","Bairro"],["lastPriceReviewDate","Revisão dos preços"]];

  return <div className="space-y-5">
    <div className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-4"><div><h1 className="font-bold">Painel da Clínica</h1><p className="text-xs text-slate-500">Acesso validado por admin_profiles.</p></div><button className={btn2} onClick={async()=>{await client?.auth.signOut();setReady(false);setLogin(true)}}><LogOut className="h-4 w-4"/>Sair</button></div>
    {msg&&<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</p>}{error&&<p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    <div className="flex gap-2 overflow-auto border-b">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap border-b-2 px-3 py-2 text-xs font-semibold ${tab===id?"border-petrol-900 text-petrol-900":"border-transparent text-slate-500"}`}>{label}</button>)}</div>

    {tab==="clinic"&&<section className="space-y-4 rounded-2xl border bg-white p-5"><div className="flex justify-between"><h2 className="font-bold">Dados da clínica</h2><button className={btn} disabled={busy} onClick={saveClinic}><Save className="h-4 w-4"/>Salvar</button></div><div className="grid gap-3 md:grid-cols-2">{cf.map(([k,l])=><Input key={k} label={l} value={String(clinic[k]??"")} onChange={v=>setClinic({...clinic,[k]:v})} type={k==="lastPriceReviewDate"?"date":k==="email"?"email":k==="mapsUrl"?"url":"text"}/>)}</div><Check label="Requer agendamento" checked={clinic.requiresAppointment??true} onChange={v=>setClinic({...clinic,requiresAppointment:v})}/><Area label="Aviso de preços" value={clinic.priceDisclaimer||""} onChange={v=>setClinic({...clinic,priceDisclaimer:v})}/></section>}

    {tab==="services"&&<section className="space-y-3"><div className="flex justify-between"><h2 className="font-bold">Serviços</h2><button className={btn} onClick={()=>{const c=categories[0];setServices([{id:crypto.randomUUID(),categorySlug:c?.slug||"consultas",categoryName:c?.name||"Consultas",name:"Novo serviço",shortDescription:"Descrição",priceType:"on_evaluation",exactPrice:null,startingPrice:null,requiresEvaluation:true,includedItems:[],availability:"Sob agendamento",isActive:true,displayOrder:services.length+1},...services])}}><Plus className="h-4 w-4"/>Novo</button></div>{services.map((x,i)=><article key={x.id} className="space-y-3 rounded-2xl border bg-white p-4"><div className="grid gap-3 md:grid-cols-2"><Input label="Nome" value={x.name} onChange={v=>setServices(services.map((q,j)=>j===i?{...q,name:v}:q))}/><Input label="Descrição" value={x.shortDescription} onChange={v=>setServices(services.map((q,j)=>j===i?{...q,shortDescription:v}:q))}/><label className="text-xs font-semibold text-slate-600">Tipo<select value={x.priceType} onChange={e=>setServices(services.map((q,j)=>j===i?{...q,priceType:e.target.value as PriceType}:q))} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="on_evaluation">Sob avaliação</option><option value="starting_at">A partir de</option><option value="exact">Fixo</option></select></label>{x.priceType!=="on_evaluation"&&<Input label="Valor" type="number" value={String(x.priceType==="exact"?x.exactPrice??"":x.startingPrice??"")} onChange={v=>setServices(services.map((q,j)=>j===i?{...q,[x.priceType==="exact"?"exactPrice":"startingPrice"]:v?Number(v):null}:q))}/>}</div><div className="flex justify-between"><Check label="Ativo" checked={x.isActive} onChange={v=>setServices(services.map((q,j)=>j===i?{...q,isActive:v}:q))}/><div className="flex gap-2"><button className={btn} onClick={()=>save("services",{id:x.id,category_id:categories.find(c=>c.slug===x.categorySlug)?.id||null,category_slug:x.categorySlug,name:x.name,short_description:x.shortDescription,price_type:x.priceType,exact_price:x.priceType==="exact"?x.exactPrice:null,starting_price:x.priceType==="starting_at"?x.startingPrice:null,requires_evaluation:x.requiresEvaluation,evaluation_notes:x.evaluationNotes||null,included_items:x.includedItems,observations:x.observations||null,availability:x.availability,is_active:x.isActive,display_order:x.displayOrder,updated_at:new Date().toISOString()})}><Save className="h-4 w-4"/>Salvar</button><button className={btn2} onClick={async()=>{if(await del("services",x.id))setServices(services.filter(q=>q.id!==x.id))}}><Trash2 className="h-4 w-4"/>Excluir</button></div></div></article>)}</section>}

    {tab==="campaigns"&&<section className="space-y-3"><div className="flex justify-between"><h2 className="font-bold">Campanhas</h2><button className={btn} onClick={()=>{const d=new Date(),e=new Date(Date.now()+2592000000);setCampaigns([{id:crypto.randomUUID(),slug:`campanha-${Date.now()}`,title:"Nova campanha",summary:"Resumo",fullDescription:"Descrição",startDate:d.toISOString().slice(0,10),endDate:e.toISOString().slice(0,10),includedServices:[],realPriceOrCondition:"Consulte a clínica",rulesAndLimitations:"Sujeito à disponibilidade",status:"draft",displayOrder:campaigns.length+1},...campaigns])}}><Plus className="h-4 w-4"/>Nova</button></div>{campaigns.map((x,i)=><article key={x.id} className="space-y-3 rounded-2xl border bg-white p-4"><div className="grid gap-3 md:grid-cols-2"><Input label="Título" value={x.title} onChange={v=>setCampaigns(campaigns.map((q,j)=>j===i?{...q,title:v}:q))}/><Input label="Slug" value={x.slug} onChange={v=>setCampaigns(campaigns.map((q,j)=>j===i?{...q,slug:v}:q))}/><Input label="Início" type="date" value={x.startDate} onChange={v=>setCampaigns(campaigns.map((q,j)=>j===i?{...q,startDate:v}:q))}/><Input label="Fim" type="date" value={x.endDate} onChange={v=>setCampaigns(campaigns.map((q,j)=>j===i?{...q,endDate:v}:q))}/><label className="text-xs font-semibold text-slate-600">Status<select value={x.status} onChange={e=>setCampaigns(campaigns.map((q,j)=>j===i?{...q,status:e.target.value as CampaignStatus}:q))} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="draft">Rascunho</option><option value="scheduled">Agendada</option><option value="active">Ativa</option><option value="ended">Encerrada</option></select></label><Input label="Condição/preço" value={x.realPriceOrCondition} onChange={v=>setCampaigns(campaigns.map((q,j)=>j===i?{...q,realPriceOrCondition:v}:q))}/></div><Area label="Resumo" value={x.summary} onChange={v=>setCampaigns(campaigns.map((q,j)=>j===i?{...q,summary:v}:q))}/><div className="flex justify-end gap-2"><button className={btn} onClick={()=>save("campaigns",{id:x.id,slug:x.slug,title:x.title,folder_image_url:x.folderImageUrl||null,summary:x.summary,full_description:x.fullDescription,start_date:x.startDate,end_date:x.endDate,eligible_audience:x.eligibleAudience||null,included_services:x.includedServices,real_price_or_condition:x.realPriceOrCondition,rules_and_limitations:x.rulesAndLimitations,download_file_url:x.downloadFileUrl||null,status:x.status,display_order:x.displayOrder,updated_at:new Date().toISOString()})}><Save className="h-4 w-4"/>Salvar</button><button className={btn2} onClick={async()=>{if(await del("campaigns",x.id))setCampaigns(campaigns.filter(q=>q.id!==x.id))}}><Trash2 className="h-4 w-4"/>Excluir</button></div></article>)}</section>}

    {tab==="faqs"&&<section className="space-y-3"><div className="flex justify-between"><h2 className="font-bold">Perguntas frequentes</h2><button className={btn} onClick={()=>setFaqs([{id:crypto.randomUUID(),category:"funcionamento",categoryName:"Funcionamento",question:"Nova pergunta",answer:"Resposta",displayOrder:faqs.length+1,isActive:true},...faqs])}><Plus className="h-4 w-4"/>Nova</button></div>{faqs.map((x,i)=><article key={x.id} className="space-y-3 rounded-2xl border bg-white p-4"><Input label="Pergunta" value={x.question} onChange={v=>setFaqs(faqs.map((q,j)=>j===i?{...q,question:v}:q))}/><Area label="Resposta" value={x.answer} onChange={v=>setFaqs(faqs.map((q,j)=>j===i?{...q,answer:v}:q))}/><div className="flex justify-between"><Check label="Ativa" checked={x.isActive} onChange={v=>setFaqs(faqs.map((q,j)=>j===i?{...q,isActive:v}:q))}/><div className="flex gap-2"><button className={btn} onClick={()=>save("faqs",{id:x.id,category:x.category,question:x.question,answer:x.answer,display_order:x.displayOrder,is_active:x.isActive,updated_at:new Date().toISOString()})}><Save className="h-4 w-4"/>Salvar</button><button className={btn2} onClick={async()=>{if(await del("faqs",x.id))setFaqs(faqs.filter(q=>q.id!==x.id))}}><Trash2 className="h-4 w-4"/>Excluir</button></div></div></article>)}</section>}

    {tab==="articles"&&<section className="space-y-3"><div className="flex justify-between"><h2 className="font-bold">Informativos</h2><button className={btn} onClick={()=>setArticles([{id:crypto.randomUUID(),slug:`informativo-${Date.now()}`,title:"Novo informativo",summary:"Resumo",category:"Prevenção",content:"Conteúdo educativo...",revisionDate:new Date().toISOString().slice(0,10),isPublished:false,displayOrder:articles.length+1},...articles])}><Plus className="h-4 w-4"/>Novo</button></div>{articles.map((x,i)=><article key={x.id} className="space-y-3 rounded-2xl border bg-white p-4"><div className="grid gap-3 md:grid-cols-2"><Input label="Título" value={x.title} onChange={v=>setArticles(articles.map((q,j)=>j===i?{...q,title:v}:q))}/><Input label="Slug" value={x.slug} onChange={v=>setArticles(articles.map((q,j)=>j===i?{...q,slug:v}:q))}/><Input label="Categoria" value={x.category} onChange={v=>setArticles(articles.map((q,j)=>j===i?{...q,category:v}:q))}/><Input label="Revisão" type="date" value={x.revisionDate} onChange={v=>setArticles(articles.map((q,j)=>j===i?{...q,revisionDate:v}:q))}/></div><Area label="Resumo" value={x.summary} onChange={v=>setArticles(articles.map((q,j)=>j===i?{...q,summary:v}:q))}/><Area label="Conteúdo" rows={7} value={x.content} onChange={v=>setArticles(articles.map((q,j)=>j===i?{...q,content:v}:q))}/><div className="flex justify-between"><Check label="Publicado" checked={x.isPublished} onChange={v=>setArticles(articles.map((q,j)=>j===i?{...q,isPublished:v}:q))}/><div className="flex gap-2"><button className={btn} onClick={()=>save("articles",{id:x.id,slug:x.slug,title:x.title,summary:x.summary,category:x.category,content:x.content,revision_date:x.revisionDate,technical_reviewer_name:x.technicalReviewerName||null,technical_reviewer_crmv:x.technicalReviewerCrmv||null,is_published:x.isPublished,display_order:x.displayOrder,updated_at:new Date().toISOString()})}><Save className="h-4 w-4"/>Salvar</button><button className={btn2} onClick={async()=>{if(await del("articles",x.id))setArticles(articles.filter(q=>q.id!==x.id))}}><Trash2 className="h-4 w-4"/>Excluir</button></div></div></article>)}</section>}
  </div>;
}
